apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: u3ms0s8vc-python 
  janus-idp.io/tekton: u3ms0s8vc-python
  backstage.io/kubernetes-id: u3ms0s8vc-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u3ms0s8vc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml