apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: u3ms0s8vc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u3ms0s8vc-python 
  name: u3ms0s8vc-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: u3ms0s8vc-python
    weight: 100 
