apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u3ms0s8vc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u3ms0s8vc-python 
  name: u3ms0s8vc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u3ms0s8vc-python 
